### ISSUE TITLE
CPU use spikes when any property inspectors are loaded

### ISSUE THREAD

**Issue by PaigeM89** [nicollasricas/vscode-streamdeck#27]
Once I've opened any property inspectors, the whole streamdeck application slows to a crawl. If I change profiles to one without any VSCode plugins & try to add actions for unrelated plugins (like, say, Text or Open under System), the application still chews up CPU and runs poorly. If I have the app open, with no VSCode actions, and use VSCode, the app is fine. If I use VSCode for a bit and then modify/add actions that aren't VSCode actions, the app is fine. Once I've gotten myself into the "chew up CPU when using the app" state, restarting fixes it (as long as I don't load any VSCode plugins). Other applications, such as VSCode itself, remain unaffected.

So there's definitely something weird happening with the property inspector(s) on my machine. I didn't see anything of interest in the streamdeck logs, nor in the logs in the VSCode plugin folder. Both `pluginlog.log` and `logs/log000.log` primarily contain a bunch of `ChangeActiveSessionMessage` logs. `pluginlog.log` does contain a couple `Error: Address already in use` logs, if those seem relevant.

The VSCode `Stream Deck` output shows it connecting & disconnecting multiple times per second (with no additional output), which doesn't seem great. I was able to get the actions to work at one point, but currently they're all just giving me alerts.

I'm on StreamDeck `4.9.3 (13222)`, firmware `1.0.191203`, MacOS Catalina `10.15.7`.

**Comment by PaigeM89** [comment]
This may have been fixed by PR #24 so we may just need a new release.

**Comment by nicollasricas** [comment]
Are you using WSL? If you are, could you please try [this](https://github.com/nicollasricas/vscode-streamdeck/issues/9#issuecomment-817202128) version?

Please look if there's more than one instance opened of "com.nicollasr.streamdeckvsc.exe" process, it may be the cause for the error: `Error: Address already in use` or the server port is already been used.

Since the address is already in use the client couldn't connect and keep trying to reconnect which was causing a high CPU usage as reported and already fixed by #24.

This fix also changes the extension kind to UI which is supposed to work with WSL without any additional configuration, but I don't use WSL and couldn't test it that's why I postpone the update.

I will release an update with the high CPU usage fix only.

Please add the pluginlog.log and vs code extension output here.

**Comment by PaigeM89** [comment]
I'm on Mac, so no WSL. I tried that version but the issue persists; my CPU is chewed up when the stream deck app (the action editor, does it have an actual name?) is opened and I'm trying to edit the VSCode actions.

I did try that extension update but the issue remains.

I'm only seeing one instance of the plugin running, though it's possible that there were 2 when that error was logged.

[pluginlog.log](https://github.com/nicollasricas/vscode-streamdeck/files/6454464/pluginlog.log)

The VSCode extension output is:
```
[5/10/2021, 3:03:25 PM] Connecting to Stream Deck
[5/10/2021, 3:03:25 PM] Registering session c498c98a-5894-47da-a6de-9ec60b7cca2c1620673399659
[5/10/2021, 3:03:25 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:03:30 PM] Connecting to Stream Deck
[5/10/2021, 3:03:31 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:03:36 PM] Connecting to Stream Deck
[5/10/2021, 3:03:36 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:03:41 PM] Connecting to Stream Deck
[5/10/2021, 3:03:42 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:03:47 PM] Connecting to Stream Deck
[5/10/2021, 3:03:47 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:03:52 PM] Connecting to Stream Deck
[5/10/2021, 3:03:54 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[... some lines skipped here, all the same thing ...]
[5/10/2021, 3:10:02 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:07 PM] Connecting to Stream Deck
[5/10/2021, 3:10:08 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:13 PM] Connecting to Stream Deck
[5/10/2021, 3:10:13 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:18 PM] Connecting to Stream Deck
[5/10/2021, 3:10:18 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:23 PM] Connecting to Stream Deck
[5/10/2021, 3:10:23 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:28 PM] Connecting to Stream Deck
[5/10/2021, 3:10:28 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:33 PM] Connecting to Stream Deck
[5/10/2021, 3:10:34 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:39 PM] Connecting to Stream Deck
[5/10/2021, 3:10:41 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:46 PM] Connecting to Stream Deck
[5/10/2021, 3:10:46 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:51 PM] Connecting to Stream Deck
[5/10/2021, 3:10:51 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:10:56 PM] Connecting to Stream Deck
[5/10/2021, 3:10:56 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:11:01 PM] Connecting to Stream Deck
[5/10/2021, 3:11:01 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:11:06 PM] Connecting to Stream Deck
[5/10/2021, 3:11:06 PM] Disconnected from Stream Deck. Reconnecting in 5 seconds.
[5/10/2021, 3:15:04 PM] Message received, ActiveSessionChangedMessage.: {"id":"ActiveSessionChangedMessage","data":"{\"sessionId\":\"c498c98a-5894-47da-a6de-9ec60b7cca2c1620673399659\"}"}
[5/10/2021, 3:15:15 PM] Message received, ActiveSessionChangedMessage.: {"id":"ActiveSessionChangedMessage","data":"{\"sessionId\":\"c498c98a-5894-47da-a6de-9ec60b7cca2c1620673399659\"}"}
[5/10/2021, 3:16:16 PM] Message received, ActiveSessionChangedMessage.: {"id":"ActiveSessionChangedMessage","data":"{\"sessionId\":\"c498c98a-5894-47da-a6de-9ec60b7cca2c1620673399659\"}"}
```

A little bit more fiddling did produce those last lines. I started creating & editing some actions. The whole UI lagged pretty severely but the "disconnect/reconnect" messages stopped.

**Comment by nicollasricas** [comment]
There weren't any errors that caused the plugin to CTD... the only reason I could think of is the property inspector.

- Enable stream deck action [inspector debug](https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#Debugging)
	`defaults write com.elgato.StreamDeck html_remote_debugging_enabled -bool YES`
- Restart Stream Deck software
- Add a new action **(INSERT SNIPPET)** into a empty folder on Stream Deck software
- Click in this action and wait for the property inspector to load (it should appear the default field (Title) and more.
	
![image](https://user-images.githubusercontent.com/7860985/117735692-f7db1000-b1c3-11eb-9baf-38c0fdf83aea.png)

- Go to http://localhost:23654
- Click on `com.nicollasr.streamdeckvsc.insertsnippet PI`
- Click in the console TAB and see if there are any errors.

**Comment by PaigeM89** [comment]
I didn't see any console logs for that action.

I had to restart my machine for an unrelated reason and now I can't recreate the issue :) Sorry for wasting any time - you can close this, I'll re-open if I can intentionally recreate the issue.
